[package]
name = "brilm"
version = "0.1.0"
edition = "2024"

[dependencies]
melior = { version = "0.26.0", features = ["ods-dialects"] }
bril-rs = { path = "..", features = ["memory"] }
serde_json = "1.0"
